#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libhandy
Version  : 0.0.9
Release  : 1
URL      : https://source.puri.sm/Librem5/libhandy/-/archive/v0.0.9/libhandy-v0.0.9.tar.gz
Source0  : https://source.puri.sm/Librem5/libhandy/-/archive/v0.0.9/libhandy-v0.0.9.tar.gz
Summary  : Library full of GTK+ widgets for mobile phones
Group    : Development/Tools
License  : LGPL-2.1 LGPL-2.1+
Requires: libhandy-bin = %{version}-%{release}
Requires: libhandy-data = %{version}-%{release}
Requires: libhandy-lib = %{version}-%{release}
Requires: libhandy-license = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : glib-dev
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pygobject

%description
# Handy
[![Pipeline status](https://source.puri.sm/Librem5/libhandy/badges/master/build.svg)](https://source.puri.sm/Librem5/libhandy/commits/master)
[![Code coverage](https://source.puri.sm/Librem5/libhandy/badges/master/coverage.svg)](https://source.puri.sm/Librem5/libhandy/commits/master)

%package bin
Summary: bin components for the libhandy package.
Group: Binaries
Requires: libhandy-data = %{version}-%{release}
Requires: libhandy-license = %{version}-%{release}

%description bin
bin components for the libhandy package.


%package data
Summary: data components for the libhandy package.
Group: Data

%description data
data components for the libhandy package.


%package dev
Summary: dev components for the libhandy package.
Group: Development
Requires: libhandy-lib = %{version}-%{release}
Requires: libhandy-bin = %{version}-%{release}
Requires: libhandy-data = %{version}-%{release}
Provides: libhandy-devel = %{version}-%{release}
Requires: libhandy = %{version}-%{release}

%description dev
dev components for the libhandy package.


%package lib
Summary: lib components for the libhandy package.
Group: Libraries
Requires: libhandy-data = %{version}-%{release}
Requires: libhandy-license = %{version}-%{release}

%description lib
lib components for the libhandy package.


%package license
Summary: license components for the libhandy package.
Group: Default

%description license
license components for the libhandy package.


%prep
%setup -q -n libhandy-v0.0.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552494990
export LDFLAGS="${LDFLAGS} -fno-lto"
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/libhandy
cp COPYING %{buildroot}/usr/share/package-licenses/libhandy/COPYING
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/handy-0.0-demo

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Handy-0.0.typelib
/usr/share/gir-1.0/*.gir
/usr/share/vala/vapi/libhandy-0.0.deps
/usr/share/vala/vapi/libhandy-0.0.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/libhandy-0.0/handy.h
/usr/include/libhandy-0.0/hdy-action-row.h
/usr/include/libhandy-0.0/hdy-arrows.h
/usr/include/libhandy-0.0/hdy-column.h
/usr/include/libhandy-0.0/hdy-combo-row.h
/usr/include/libhandy-0.0/hdy-dialer-button.h
/usr/include/libhandy-0.0/hdy-dialer-cycle-button.h
/usr/include/libhandy-0.0/hdy-dialer.h
/usr/include/libhandy-0.0/hdy-dialog.h
/usr/include/libhandy-0.0/hdy-enum-value-object.h
/usr/include/libhandy-0.0/hdy-enums.h
/usr/include/libhandy-0.0/hdy-expander-row.h
/usr/include/libhandy-0.0/hdy-fold.h
/usr/include/libhandy-0.0/hdy-header-group.h
/usr/include/libhandy-0.0/hdy-leaflet.h
/usr/include/libhandy-0.0/hdy-list-box.h
/usr/include/libhandy-0.0/hdy-main.h
/usr/include/libhandy-0.0/hdy-search-bar.h
/usr/include/libhandy-0.0/hdy-string-utf8.h
/usr/include/libhandy-0.0/hdy-title-bar.h
/usr/include/libhandy-0.0/hdy-value-object.h
/usr/include/libhandy-0.0/hdy-version.h
/usr/lib64/libhandy-0.0.so
/usr/lib64/pkgconfig/libhandy-0.0.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libhandy-0.0.so.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libhandy/COPYING
